config/routes.rb
Rails.application.routes.draw do
  root 'submit#new'

  get 'my_test/action1'
  get 'my_test/action2'

  get 'about' => 'framework#about'
  get 'help' => 'framework#help'
  get 'test/action1' => 'my_test#action1'
  get 'test/action2' => 'my_test#action2'
  get 'submit/empty_cell_type'
  resources :submit, param: :name, only: [:new, :create, :edit, :show]
  resources :download, param: :name, only: [:show]

end

app/models/cell_type.rb
class CellType < ActiveRecord::Base
  belongs_to :species
  belongs_to :sample_class
  validates :desc, presence: true
  validates_uniqueness_of :desc, scope: [:species_id]
  scope :info, -> {CellType.joins(:species, :sample_class).
      order('species.id, sample_classes.id, cell_types.id').
      select('species.name as species_name,
              sample_classes.desc as sample_class_desc,
              cell_type.id
              cell_types.desc')}
end

app/models/expression.rb
class Expression < ActiveRecord::Base
  belongs_to :transcript
  belongs_to :cell_type
  has_one :submit, through: :transaction
  validates :value, presence: true
end

app/models/sample_class.rb
class SampleClass < ActiveRecord::Base
  has_many :cell_types
  validates :desc, presence: true, uniqueness: true
end

app/models/species.rb
class Species < ActiveRecord::Base
  has_many :cell_types
  has_many :sample_classes, through: :cell_types
  validates :name, presence: true, uniqueness: true
end

app/models/submit.rb
class Submit < ActiveRecord::Base
  has_many :transcripts
  has_many :cell_types, through: :expressions
  has_many :expressions, through: :transcripts
  validates :name, presence: true, uniqueness: true
  scope :get_exp, ->(submit_id) { Expression.joins(:transcript, {cell_type: :sample_class}).
      where('transcripts.submit_id = ?', submit_id).
      order('transcripts.id, sample_classes.id, cell_types.id').
      select("transcripts.name as trans_name,
              sample_classes.desc as sample_class_desc,
              cell_types.desc as cell_type_desc,
              expressions.value as value") }
end

app/models/transcript.rb
class Transcript < ActiveRecord::Base
  belongs_to :submit
  has_many :cell_types, through: :expressions
  has_many :expressions
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/download_controller.rb
class DownloadController < ApplicationController
  def show
    submit_name = params[:name]
    file_path_to_download = get_file_path_to_download(submit_name)
    send_file(file_path_to_download)
  end

  private

  def get_file_path_to_download(submit_name)
    file_name = "LocExpress_#{submit_name}.zip"
    File.join(ENV['RUN_DIR'], submit_name, file_name)
  end

end

app/controllers/framework_controller.rb
class FrameworkController < ApplicationController
  def index

  end

  def help

  end

  def about
  end
end

app/controllers/my_test_controller.rb
class MyTestController < ApplicationController
  def action1

  end

  def action2
  end
end

app/controllers/submit_controller.rb
class SubmitController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @cell_types_info = get_cell_type_info
  end

  def create
    # check cell types
    cell_types = check_cell_types(params[:cell_types])
    if cell_types == 'NO'
      return redirect_to root_path
    end

    # check species
    species_ids = get_species_ids(cell_types)
    species = check_species_uniq(species_ids)
    if species == 'NO'
      return redirect_to new_submit_path
    end

    @submit = Submit.create(name: generate_submit_name, status: -2)

    # write user submit content
    user_dir = prepare_user_dir(@submit.name)
    write_cell_types(cell_types, user_dir)

    if params.has_key?(:gtf_file)
      uploaded_io = params[:gtf_file]
      write_user_submit_file(uploaded_io, user_dir)
    elsif params.has_key?(:input_gtf_text)
      user_submit_text = params[:input_gtf_text]
      write_user_submit_text(user_submit_text, user_dir)
    else
      flash[:danger] = 'Invalid option!'
      return redirect_to new_submit_path
    end

    # run LocExpress
    run_loc_express(@submit, species)
    redirect_to submit_path(@submit.name)
  end

  def show
    @submit = Submit.where(name: params[:name]).first
    @cell_type_hash, @total_exp_hash = get_exp_and_cell_types(@submit)
  end

  # for ajax
  def empty_cell_type
    respond_to do |format|
      format.js { render :layout => false }
    end
  end


  # helper functions
  private

  def get_cell_type_info
    cell_types_info = []
    Species.order(:id).each do |species|
      sample_classes = []
      species.sample_classes.order(:id).distinct.each do |sample_class|
        cell_types = []
        CellType.where(species_id: species.id, sample_class_id: sample_class.id).each do |cell_type|
          cell_types.push([cell_type.id, cell_type.desc])
        end
        sample_classes.push({sample_class.desc => cell_types})
      end
      cell_types_info.push({species.name => sample_classes})
    end
    return cell_types_info
  end

  def get_species_ids(cell_types)
    CellType.select(:species_id).where("id in (#{cell_types.join(',')})").distinct.pluck(:species_id)
  end

  def check_species_uniq(species_ids)
    if species_ids.length > 1
      flash[:danger] = 'Sorry, you should only select cell types in one species.'
      return 'NO'
    else
      Species.find(species_ids).first.name
    end
  end

  def generate_submit_name
    name_exists = TRUE
    while name_exists do
      submit_name = SecureRandom.urlsafe_base64
      if not Submit.exists?(name: submit_name)
        name_exists = FALSE
        break
      end
    end
    return submit_name
  end

  def check_cell_types(raw_cell_types)
    cell_types = []
    raw_cell_types.each do |c|
      if c =~ /^\d+$/
        cell_types.push(c)
      end
    end
    if cell_types.length == 0
      flash[:danger] = 'Invalid option!'
      return 'NO'
    else
      return cell_types
    end
  end

  def get_user_dir(submit_name)
    File.join(ENV['RUN_DIR'], submit_name)
  end

  def prepare_user_dir(submit_name)
    user_dir = get_user_dir(submit_name)
    Dir.mkdir(user_dir) if not File.exists?(user_dir)
    return user_dir
  end

  def write_cell_types(cell_types, run_dir)
    output_file = File.join(run_dir, 'cell_type.list')
    File.open(output_file, 'w') {|f| f.puts(cell_types) }
  end

  def write_user_submit_text(input_gtf_text, run_dir)
    output_file = File.join(run_dir, 'input.gtf')
    File.open(output_file, 'w') {|f| f.write(input_gtf_text) }
  end

  def write_user_submit_file(uploaded_io, run_dir)
    output_file = File.join(run_dir, 'input.gtf')
    File.open(output_file, 'wb') {|f| f.write(uploaded_io.read) }
  end

  def run_loc_express(submit, species)
    user_dir = get_user_dir(submit.name)
    bin_dir = File.join(Rails.root, 'bin')
    script = File.join(bin_dir, 'run_loc_express.rb')
    log_file = File.join(user_dir, 'ruby_run.log')
    run_cmd = "#{bin_dir}/rails runner -e #{Rails.env} #{script} #{submit.id} #{species.downcase!} >#{log_file} 2>&1 &"
    puts run_cmd
    %x(#{run_cmd})
  end

  def get_exp_and_cell_types(submit)
    cell_type_desc_hash = Hash.new {|hsh, key| hsh[key] = Set[]}
    total_exp_hash = Hash.new {|hsh, key| hsh[key] =
        Hash.new {|hsh2, key2| hsh2[key2] = []}}
    exp = Submit.get_exp(submit.id)
    exp.each do |row|
      cell_type_desc_hash[row.sample_class_desc].add(row.cell_type_desc)
      total_exp_hash[row.trans_name][row.sample_class_desc].push(row.value)
    end
    return cell_type_desc_hash, total_exp_hash
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "LocExpress"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/download_helper.rb
module DownloadHelper
end

app/helpers/framework_helper.rb
module FrameworkHelper
end

app/helpers/my_test_helper.rb
module MyTestHelper
end

app/helpers/submit_helper.rb
module SubmitHelper
  def get_run_status_info(submit_status)

    if submit_status == 0
      return 'Successfully finished', 'success'
    elsif submit_status == -2
      return 'Waiting', 'warning'
    elsif submit_status == -1
      return 'Running', 'info'
    else
      return 'Failed', 'danger'
    end
  end

  def get_chart_width(cell_type_num)
    chart_width = 100 * cell_type_num
    min_width = 500
    max_width = 1100
    if chart_width <= min_width
      chart_width = min_width
    elsif chart_width >= max_width
      chart_width = max_width
    end
    return chart_width
  end

end

app/views/framework/about.html.erb
<% provide(:title, 'About') %>

<div class="row">

  <div class="col-md-12">
    <div class="page-header">
      <h1 class="lead about-header"><span class="glyphicon glyphicon-info-sign text-muted" style="font-size: 24px"></span> Information</h1>
    </div>
    <dl>
      <dt>Development Team</dt>
      <dd>Mei Hou, Feng Tian, Shuai Jiang, Dechang Yang, Lei Kong, Ge Gao</dd>
      <br>
      <dt>Publication</dt>
      <dd>Hou,M., Tian,F., Jiang,S., Yang,D., Kong,L. and Gao,G. (2016) <a href="https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-016-3329-3" target="_blank">LocExpress: a web server for efficiently estimating expression of novel transcripts.</a> <em>BMC genomics. </em>2016 17:3329</dd>
      <br>
      <dt>Contact</dt>
      <dd><a href="mailto:annolnc@mail.cbi.pku.edu.cn">loc-express@mail.cbi.pku.edu.cn</a></dd>
    </dl>
  </div>

  <div class="col-md-12">
    <div class="page-header">
      <h1 class="lead about-header"><span class="glyphicon glyphicon-paperclip text-muted" style="font-size: 24px"></span> Supplementary</h1>
    </div>
    <ul>
      <li><%= link_to "Sample and mapping information", url="#{root_path}LocExpress_sample_mapping_info.xlsx"%></li>
      <li><%= link_to "LocExpress source code", url="#{root_path}LocExpress_src.zip"%></li>
    </ul>
  </div>

</div>

app/views/framework/help.html.erb
<% provide(:title, 'FAQ') %>

<% content_for :js do %>
    <script>
      $(document).ready(function(){
        $('#nav-help').addClass('active');

        // generate the table of content
        $('#q-a>li>p').each(function() {
          var text = $(this).text();
          var id = $(this).attr('id');
          $('#table-of-content').append('<a href="#' + id + '"><li>' + text + '</li></a>')
        });

        // add target=_blank to <a>
        $('#q-a a').attr('target', '_blank')
      })
    </script>
<% end %>

<% content_for :css do %>
    <style>
      ol {
        padding-left: 20px;
      }
      #q-a>li>p {
        font-size: 20px;
        font-weight: 800;
      }

      .al-list {
        margin-bottom: 10px;
      }
    </style>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <h1 class="lead about-header"><span class="glyphicon glyphicon-th-list text-muted" style="font-size: 24px"></span> Table of Contents</h1>
    </div>
    <p><em>If you have more questions, please contact <a href="mailto:annolnc@mail.cbi.pku.edu.cn">loc-express@mail.cbi.pku.edu.cn</a>.</em></p>
    <ol id="table-of-content">
    </ol>

    <div class="page-header">
      <h1 class="lead about-header"><span class="glyphicon glyphicon-th-list text-muted" style="font-size: 24px"></span> Q&A</h1>
    </div>
    <ol id="q-a">
      <li><p id="what-is-loc-express">What is LocExpress?</p>
        <div>
          <p>
            <%= link_to "LocExpress", root_path %>  is a web server for efficiently estimating expression of novel transcripts across multiple tissues and cell types in human and mouse. For a given gene model, LocExpress estimates its abundance only based on its <strong>minimum spanning bundle (MSB)</strong> region instead of reanalyzing the whole transcriptome. Such context-oriented strategy enables <strong>the nearly real-time expression profiling for a novel transcript in hundreds of samples within minutes</strong>, with the same accuracy of standard quantification algorithms. In our evaluation, the median time for a novel transcript per sample is <strong>1.13s in human</strong> and <strong>0.43s in mouse</strong>.

          </p>
        </div>
      </li>

      <li><p id="submit-require">How do I submit transcripts? What are the requirements?</p>
        <div>
          <p>Currently, LocExpress allows the submission of transcripts in <a href="http://mblab.wustl.edu/GTF2.html">GTF</a> format. You can either paste GTF contents in the textbox or submit a file at the <%= link_to "home page", new_submit_path%> . Because LocExpress is designed for expression estimation at local region, the maximum spanning region of the GTF file should <strong>less than 1 Mb</strong> and the total line number should be <strong>within 1000</strong>.</p>
        </div>
      </li>

      <li><p id="multiple-transcripts">Can I submit multiple transcripts in one time?</p>
        <div>
          <p>Yes, LocExpress supports multiple transcripts in one submission if they meet criteria <a href="#submit-require">above</a>.</p>
        </div>
      </li>

      <li><p id="sample-info">What samples does LocExpress use for each cell type?</p>
        <div>
          <p>Please see details about sample information <a href="<%= root_path %>LocExpress_sample_mapping_info.xlsx">here</a>.</p>
        </div>
      </li>

    </ol>
  </div>
</div>

app/views/framework/index.html.erb
<p>INDEX</p>

app/views/layouts/_footer.html.erb
<div class="footer small-text-1">
  <div class="container">
    <p class="text-muted text-center" style="padding:10px; margin-bottom:0px">
      Copyright © 2016,
      <a target="_blank" href="http://www.cbi.pku.edu.cn/">Center for Bioinformatics</a>
      ,
      <a target="_blank" href="http://www.pku.edu.cn/">Peking University</a>
      All Rights Reserved.
    </p>
  </div>
</div>

<script>
  $(document).ready(function(){
    $('.footer').css('position', $(document).height() > $(window).height() ? "inherit" : "fixed");
  })
</script>

<% if Rails.env.production? %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-70605144-2', 'auto');
  ga('send', 'pageview');

</script>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse"
              class="navbar-toggle collapsed" type="button">
        <span class="sr-only"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to raw('<b style="color: #d3d3d3">LocExpress</b>'), root_path, :class => "navbar-brand"%>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-left">
        <li> <%= link_to "FAQ", help_path %></li>
        <li> <%= link_to "About", about_path %></li>
      </ul>
    </div>
  </div>
</header>

app/views/my_test/action1.html.erb
<h1>MyTest#action1</h1>
<p>Find me in app/views/my_test/action1.html.erb</p>

app/views/my_test/action2.html.erb
<h1>MyTest#action2</h1>
<p>Find me in app/views/my_test/action2.html.erb</p>

app/views/submit/create.html.erb
<h1>Submit#create</h1>
<p>Find me in app/views/submit/create.html.erb</p>

app/views/submit/new.html.erb
<% provide(:title, 'Submit') %>

<% content_for :css_include do %>
    <link rel="stylesheet" href="<%= root_path %>jstree/dist/themes/proton/style.min.css" />
<% end %>

<% content_for :js_include do %>
    <script src="<%= root_path %>jstree/dist/jstree.min.js"></script>
<% end %>

<% content_for :css do%>
    <style>
      #input-gtf-text::-webkit-input-placeholder {
        font-size: 17px;
        font-weight: 500;
        color: #808080
      }
      #input-gtf-text::-moz-placeholder {
        font-size: 17px;
        font-weight: 500;
        color: #808080
      }
    </style>
<% end %>

<% content_for :js do %>
    <script>
      $('document').ready(function(){

        $('#check-box-tree').jstree({
          'plugins': ["wholerow", "checkbox"],
          'core': {
            'themes': {
              'name': 'proton',
              'responsive': true,
              "icons":false
            }
          }
        });

        // select the normal tissue of human
        var human_normal_tissue = $('#check-box-tree ul li:first ul:first li:first a')[0];
        human_normal_tissue.click();

        // ajax for try out trans ajax
        $('#demo-gtf li').click(function(){
          var name = $(this).find('a').text();
          var url = '<%= root_path %>' + 'tryout_trans/' + name + '.gtf';
          $.get(url, function(data, status){
            $('#input-gtf-text').val(data)
          });
        });

        // for the try out trans like clickable
        $('#submit-form li a').attr('href', 'javascript:void(0)');

        // process parameters before submit
        $('#submit-form').submit(function(){
          var content = $(this).find('.user-content').val();
          var gtf_file = $('#gtf_file')[0].files[0];
          var gtf_is_defined = (undefined != gtf_file);

          // empty content and not upload file
          if (content == '' && (! gtf_is_defined)) {
            return false
          }
          // empty file uploaded
          else if (gtf_is_defined && gtf_file.size == 0) {
            alert('Empty file!');
            return false
          }
          else if (gtf_is_defined && gtf_file.size > 1048576) { // 1M
            alert('File size should be less than 1M!');
            return false
          }
          else {
            // in case text box and file are all filled //
            if (content != '' && gtf_is_defined && gtf_file.length != 0) {
              alert('Only content in the file will be processed.')
            }

            // check the selected items //
            var raw_cell_types = $('#check-box-tree').jstree("get_selected");
            if (raw_cell_types.length == 0) {
              // warn no items selected //
              $.get({
                url: "<%= submit_empty_cell_type_path %>",
                data: '',
                dataType: 'html',
                success: function(data) {
                  $('#warn-empty-item').html(data)
                }
              });
              return false
            } else {
              // for the submit //
              // 0. remove all previous input
              $('#submit-form').find("input[name='cell_types[]']").remove();
              var cell_types = [];
              for (var i in raw_cell_types) {
                var cell_type = raw_cell_types[i];
                // 1.  filter selected IDs added by jsTree
                if (cell_type.substring(0, 1) != "j") {
                  // 2. add the selected items value to form parameters
                  var input = $("<input>")
                      .attr("type", "hidden")
                      .attr("name", "cell_types[]").val(cell_type);
                  $('#submit-form').append($(input));
                }
              }
            }
          }
        });

      });

    </script>
<% end %>

<div class="row">
  <div class="col-md-12">
    <h1 class="text-center big-title">LocExpress</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12" id="warn-empty-item">

  </div>
</div>

<div class="row" style="margin-top: 4%; margin-bottom: 5%">
  <div class="col-md-3">
    <div id="check-box-tree">
      <ul>
        <%
          @cell_types_info.each do |species_hash|
            species_hash.each do |species, sample_class_list|
        %>
                <li class="jstree-open"><%= species %>
                  <% sample_class_list.each do |sample_class_hash| %>

                      <ul>
                        <% sample_class_hash.each do |sample_class, cell_type_list| %>
                            <li><%= sample_class %>
                              <ul>
                                <% cell_type_list.each do |cell_type| %>
                                    <li id="<%= cell_type[0] %>" class="cell-type"><%= cell_type[1] %></li>
                                <% end %>
                              </ul>
                            </li>
                        <% end %>
                      </ul>
                  <% end %>
            <% end %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="col-md-8 col-md-offset-1">

    <form id="submit-form" role="form" method="post" action="<%= submit_index_path %>" enctype="multipart/form-data">
      <textarea id="input-gtf-text" name="input_gtf_text" class="form-control user-content" rows="20" placeholder="LocExpress is a web server for real-time expression estimation of novel transcripts. You can paste transcript models in GTF format here. Now LocExpress supports human transcripts based on hg38 and mouse transcripts based on mm10."></textarea>

      <div class="help-block" style="margin-top: 20px">
        <ul class="list-inline" id="demo-gtf">
          <li>Try out:</li>
          <li><a>Demo_1</a></li>
          <li><a>Demo_2</a></li>
          <li><a>Demo_3</a></li>
          <li><a>Demo_4</a></li>
          <li><a>Demo_5</a></li>
        </ul>
      </div>

      <div class="row" style="margin-top: 20px;">

        <div class="col-md-10">
          <div class="form-group">
            <label for="file" class="large-text-1">Or you can upload a GTF file</label>
            <input type="file" name="gtf_file" id="gtf_file">
          </div>
        </div>

        <div class="col-md-2">
          <button type="submit" class="btn btn-success btn-block" style="" id="seq-go">GO</button>
        </div>

      </div>
    </form>
  </div>
</div>

app/views/submit/show.html.erb
<% provide(:title, 'Result') %>
<%
  result_url = submit_url(@submit.name)
  status_info, class_to_add = get_run_status_info(@submit.status)
  trans_num = @total_exp_hash.length
  trans_name_list = @total_exp_hash.keys
  if trans_num > 0
    sample_class_list = @total_exp_hash.first[1].keys
  end
%>


<% content_for :js_include do %>
    <%= javascript_include_tag 'submit.js' %>
<% end %>

<% content_for :css_include do %>
<% end %>

<% content_for :js do %>
    <script>
      var cle = '';
      var totalSec = 30;
      function clear_cle() {
        if (this.cle != '') {
          window.clearInterval(this.cle);
        }
      }

      function countTime() {
        this.second =  this.totalSec;
        this.cle = setInterval('flushCount()', 1000)
      }

      function flushCount() {
        this.second --;
        if(this.second <= 0) {
          // stop current counting
          clear_cle();
          window.location.reload(true);
//          refreshStatus();
//          this.second = this.totalSec
        } else {
          $('#le-time').text(this.second)
        }
      }

      function refreshStatus() {
        $('#not-finished').removeClass('le-hide');
        countTime();
      }

      $(document).on('ready page:load', function(){

        // for time fresh //
        clear_cle();
        var status_code = <%= @submit.status %>;
        if (status_code < 0) {
          refreshStatus();
        }

        // add class to run status //
        $('#run-status').addClass('<%= class_to_add %>');

        // make the first column of table to bold //
        $('#summary tr td:nth-child(1)').addClass('le-bold');

        // for display expression //
        <% if trans_num > 0%>
        var total_exp_hash = JSON.parse('<%= raw @total_exp_hash.to_json %>');

        // for keeping order
        var trans_name_list = JSON.parse('<%= raw trans_name_list %>');
        var sample_class_list = JSON.parse('<%= raw sample_class_list %>');
        var cell_type_hash = JSON.parse('<%= raw @cell_type_hash.to_json %>');

        // draw bar plot for each transcript
        $('.exp-panel').each(function(i) {
          var trans_name = trans_name_list[i];

          // 1. add panel related classes and IDs
          var panel_id = 'collapse-' + i;
          var ref_panel_id = '#' + panel_id;

          // 1.1 add for panel head
          $(this).find('.panel-heading a').attr({'data-target': ref_panel_id, 'href': ref_panel_id});

          // 1.2 add for panel body
          var panel_body = $(this).find('.for-panel-body');
          panel_body.attr('id', panel_id);

          // 1.3 expand first 3 panels
          if (i <= 3) panel_body.addClass('in');

          // 2.  draw exp bar plot for each sample class
          panel_body.find('.exp-chart').each(function(c) {
            var sample_class = sample_class_list[c];
            exp_list = total_exp_hash[trans_name][sample_class];

            // 2.1 prepare
            var exp_max = null;
            if (Math.max.apply(null, exp_list) < 1) exp_max = 1.5;

            // 2.2. draw
            $(this).highcharts({
              credits: {
                enabled: false
              },
              chart: {
                type: 'column'
              },
              title: {
                text: 'Expression Profile in ' + sample_class
              },
              xAxis: {
                'categories': cell_type_hash[sample_class],

                labels: {
                  rotation: -30,
                  style: {
                    fontSize: '12px',
                    fontFamily: 'Verdana, sans-serif'
                  }
                }
              },
              yAxis: {
                gridLineWidth: 0,
                lineWidth: 1,
                min: 0,
                max: exp_max,
                title: {
                  text: 'FPKM'
                }
              },
              legend: {
                enabled: false
              },
              tooltip: {
                pointFormat: 'FPKM: {point.y:.2f}'
              },

              series: [
                {
                  name: 'FPKM',
                  maxPointWidth: 50,
                  color: '#0275da',
                  data: exp_list

                }
              ]
            }); // chart end
          });

        });
        <% end %>
      })
    </script>
<% end %>

<% content_for :css do %>
    <style>

    </style>
<% end %>

<div class="row">
  <div class="col-md-12">
    <%=	link_to 'Start a new job', new_submit_url, class: 'btn btn-success', role: 'button', target: '_blank' %>
    <!--<a href="" class="btn btn-primary btn-lg disabled" role="button">Primary link</a>-->
  </div>
</div>

<div class="row" style="margin-top: 20px">
  <div class="col-md-12">
    <div class="panel panel-info le-hide" id="not-finished">
      <div class="panel-heading">
        Thanks for using LocExpress
      </div>
      <div class="panel-body">
        <p style="margin-bottom: 10px">This page will be refreshed in <strong class="large-text-2" id="le-time"></strong> sec...Or you can click <%= link_to 'here', result_url, class: 'le-bold'%> to manually refresh. </p>
      </div>
    </div>
  </div>

</div>

<div class="row">
  <div class="col-md-12">
    <div class="table-responsive" style="margin-top: 20px">
      <table class="table table-striped" id="summary">
        <tr>
          <td>Result URL</td>
          <td><%= link_to result_url, result_url%></td>
        </tr>

        <% if @submit.status == 0 %>
            <tr>
              <td>Download URL</td>
              <% user_download_url = download_url(@submit.name) %>
              <td><%= link_to user_download_url, user_download_url %></td>
            </tr>
        <% end %>

        <% if trans_num > 0 %>
          <tr>
            <td>Number of transcripts</td>
            <td><%= trans_num %></td>
          </tr>
        <% end %>
        <tr id="run-status">
          <td>Run Status</td>
          <td><%= status_info %></td>
        </tr>
       <% if @submit.status > 0 %>
            <tr>
              <td>Error message</td>
              <td><%= @submit.msg %></td>
            </tr>
        <% end %>
      </table>
      <div></div>
    </div>
  </div>
</div>

<% if trans_num > 0 %>
    <div class="row" style="margin-top: 20px">
      <div class="col-md-12">
        <%= render partial: "submit/expression",
                   collection: trans_name_list, as: 'trans_name',
                   locals: {sample_class_num: sample_class_list.length,
                   cell_type_num_list: @cell_type_hash.map {|k, v| v.length}}
        %>
      </div>
    </div>
<% end %>